language: java
install: mvn clean && mvn compile && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
after_success:
  - mvn sonar:sonar -Dsonar.organization=arvinsichuan-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
notifications:
  email:
    - Arvinsc@foxmail.com